### PR TITLE
add a close channel in order to finish the dial loop

### PR DESCRIPTION
**Pull request by p4u**
This is required in order to terminate the connect() lopp.

If this is not applied, after calling Close() the connect goroutine would keep iterating and trying to reconnect

Signed-off-by: p4u <pau@dabax.net>

### CODE REVIEW

**Comment by loeffel-io** [comment]
thanks for your contribution! 

btw: is this also solving #20 ?

**Comment by p4u** [comment]
Probably yes, but I am not sure if there is some other corner case that could trigger this issue.

**Comment by loeffel-io** [comment]
alright, thanks man

**Comment by loeffel-io** [comment]
released in v1.2.2

**Pull request merged**
